# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - inspredict

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://insurancepred.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_37ae119bf41c41f4be064f870115d93a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c482d0c34b5944319fd445136282542b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: insurancepred.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_37ae119bf41c41f4be064f870115d93a }}/insuranceprediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inspredict'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f387beb77d174e899c67ad6c24a51554 }}
        images: 'insurancepred.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_37ae119bf41c41f4be064f870115d93a }}/insuranceprediction:${{ github.sha }}'